name: Deploy Vue App to Nginx

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit & E2E Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests (Vitest)
      run: npm run test:unit

    - name: Run E2E Tests (Cypress)
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        browser: chrome

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test  # Only run this job if tests pass

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Vue App
      run: npm run build

    - name: Deploy to Server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "dist/*"
        target: "/var/www/vue-app/"

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          sudo systemctl restart nginx
